### ISSUE TITLE
running valine on CentOS 6 gives error: column: invalid option -- 'o'

### ISSUE THREAD

**Issue by kenanrizvic** [ryran/valine#26]
Hi

Me again :)
Is there something i missing in versions you use for bash/libvirt or there is something incomplete in code.

Just start valine gives me this :

```
[root@xen2 ~]# valine 
column: invalid option -- 'o'
usage: column [-tx] [-c columns] [file ...]

Key:
  • Each domain's current storage is marked with a green arrow: ←
  • Storage which is revertable & Deletable is displayed in cyan

[root@xen2 ~]# 
```

I found that column version column  i use is util-linux-ng-2.17.2-12.14.el6.x86_64 and there is no option -o. I tried to put to -c insted -o 

```
[root@xen2 ~]# diff myversion.sh bin/valine 
570c570
<         column -t -s "❚" -c " │ " |

---
>         column -t -s "❚" -o " │ " |
```

and i got this output :

```
./1.sh: line 319: /var/lib/valine/informix-21-222_4: No such file or directory
./1.sh: line 339: /var/lib/valine/informix-21-222_4: No such file or directory
Warning: informix-21-222_4 config file has improper CfgVersion ('0Sifr' expected)
Storage displayed for this domain might not be accurate
If this causes problems, delete /var/lib/valine/informix-21-222_4
─DOMAIN──────────────⚡──STORAGE───SNAPSHOTS──────────────────────────────────────────
 Domain-0            ◉  unknown    ←
─informix-21-222_4───◉──lvm───────/dev/vmspace/informix-21-222_4─←──────────────────────────────────────────
─privremeno──────────◌──unknown───/backup/systemrescuecd-x86-4.2.0.iso─←──────────────────────────────────────────

Key:
  • Each domain's current storage is marked with a green arrow: ←
  • Storage which is revertable & Deletable is displayed in cyan


```

Am i doing something  wrong or missing prerequisites list somewhere. How to make files /var/lib/valine/\* and are they  required.

Best Regards
Kenan

**Comment by ryran** [comment]
@kenanrizvic 
Hi Kenan. Yeah I should have thought about that when you mentioned in the last issue that you were on CentOS 6. I designed this a couple years ago around the Fedora 20 / RHEL 7 release. I've never tried to play around with RHEL 6 to see what kind of changes would need to be made -- I have neither the time nor the physical machines to do so.

**Comment by kenanrizvic** [comment]
It's ok. Just write in  readme or similar list of expected env .
If i have time , i will try to make it work on centos 6 and test  it.  Anyway very good tool and good idea .
For me this issue can be closed.
Keep good work.

Best Regards
Kenan
